[book]
authors = ["Vasiliy Kupriakov", "Alexey Gorovoi", "Nikita Sintsev", "Ivan Bagrov", "Evgenii Mukha"]
language = "en"
multilingual = false
src = "src"
title = "FHIRSchema"

[output.html.code.hidelines]
yaml = "~"
