name: tests
on:
  push:
    branches: [ '*' ]
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    name: Test fhirschema.js
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Run tests
        working-directory: fhirschema-js
        run: bun run test
        continue-on-error: false
